#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Test_Android.Resource", IsApplication=true)]

namespace Test_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int ContextMenuButton = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int LoopTest_Elapsed = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int LoopTest_Start = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int LoopTest_Stop = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int LoopTests = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int PickFileButton = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int PickFilesButton = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int PickFolderButton = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int RegisteredContextMenu = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int TestContextMenuButton = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int TestFilePickerButton = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BindingTests = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContextMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoopTests = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Pickers = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
